var mongoose = require('mongoose');
var VILKerala = mongoose.model('sites',
{
    RFID:{type:String, required:true },
    InfraID:{type:String, required:true},
    InfraOwner:{type:String, required:true},
    SiteName:{type:String, required:true},
    Zone:{type:String, required:true},
    District:{type:String, required:true},
    TowerType:{type:String, required:true},
    TowerHeight:{type:Number, required:true},
    SiteType:{type:String, required:true},
    OtherOPCOCount:{type:Number, required:true},
    BBUPosition:{type:String, required:true},
    BBULocation:{type:String, required:true},
    RRUCount2G:{type:Number, required:true},
    RRUCount3G4G:{type:Number, required:true},
    TDDRRUCount:{type:Number, required:true},
    MIMORRUCount:{type:Number, required:true},
    TotalRRUCount:{type:Number, required:true},
    AntennaCount2Port:{type:Number, required:true},
    AntennaCount4Port:{type:Number, required:true},
    AntennaCount6Port:{type:Number, required:true},
    AntennaCount8Port:{type:Number, required:true},
    AntennaCount10Port:{type:Number, required:true},
    MWMake:{type:String, required:true},
    MWModel:{type:String, required:true},
    MWLocation:{type:String, required:true},
    MWPosition:{type:String, required:true},    
    MWCount:{type:Number, required:true},
    ILLDependnecy:{type:String, required:true},
    AntennaCountPoint3:{type:Number, required:true},
    AntennaDirectionsPoint3:{type:String, required:true},    
    AntennaCountPoint6:{type:Number, required:true},
    AntennaDirectionsPoint6:{type:String, required:true},    
    AntennaCountPoint9:{type:Number, required:true},
    AntennaDirectionsPoint9:{type:String, required:true},
    AntennaCount1Point2:{type:Number, required:true},
    AntennaDirections1Point2:{type:String, required:true},
    AntennaCount1Point8:{type:Number, required:true},
    AntennaDirections1Point8:{type:String, required:true},
    MUXMake:{type:String, required:true},
    MUXModel:{type:String, required:true},
    MUXLocation:{type:String, required:true},
    MUXPosition:{type:String, required:true},
    MUXCount:{type:Number, required:true},
    LastUpdate:{type:String}
        
})
module.exports={VILKerala}



